#!/usr/bin/env python3
"""
Fix AI-generated youth players in Chinese teams who have English names
but nationality set to 'China'. Replaces them with proper Chinese names.

Usage:
    python3 scripts/fix_chinese_names.py [path_to_save.db]

If no path is given, tries the default save location.
"""

import sqlite3
import random
import sys
import os
from pathlib import Path

# Chinese surname pool (30 surnames)
SURNAMES = [
    "王", "李", "张", "刘", "陈", "杨", "赵", "黄", "周", "吴",
    "徐", "孙", "胡", "朱", "高", "林", "何", "郭", "马", "罗",
    "梁", "宋", "郑", "谢", "韩", "唐", "冯", "董", "肖", "田",
]

# Chinese given name pool (79 given names, 2 chars each)
GIVEN_NAMES = [
    "志强", "伟杰", "明辉", "浩宇", "俊杰", "建平", "志明", "永强", "建国", "文杰",
    "海涛", "卫东", "建华", "志伟", "嘉诚", "瑞华", "晓明", "洪波", "泽宇",
    "天佑", "宇轩", "子涵", "梓豪", "雨泽", "俊豪", "博文", "鹏飞", "伟国", "振华",
    "家豪", "明杰", "志鹏", "嘉豪", "瑞祥", "庆丰", "德明", "光华", "世杰",
    "宏亮", "国栋", "海峰", "文斌", "永春", "金明", "秀峰", "玉林", "宝山", "福生",
    "少华", "广平", "庆华", "建峰", "惠明", "瑞林", "洪亮", "志坚",
    "伟民", "永康", "胜军", "长春", "新宇", "云龙", "大军", "克强",
    "宗伟", "永林", "金水", "德福", "贵生", "玉山", "富贵", "万全",
    "文涛", "建新", "海波", "瑞鑫", "铭泽", "景辉", "卫平",
]

def find_save_file(path=None):
    if path:
        p = Path(path)
        if p.exists():
            return p
        print(f"File not found: {path}")
        sys.exit(1)
    
    # Try default locations
    candidates = [
        Path.home() / ".local/share/openfootmanager/saves",
        Path.home() / "Library/Application Support/openfootmanager/saves",
    ]
    for saves_dir in candidates:
        if saves_dir.exists():
            dbs = list(saves_dir.glob("*.db"))
            if dbs:
                return dbs[0]
    
    print("No save file found. Provide path manually.")
    sys.exit(1)


def fix_players(db_path):
    conn = sqlite3.connect(str(db_path))
    cursor = conn.cursor()
    
    # Find all players with nationality 'China' whose names look non-Chinese
    # (ai_youth_ prefix players generated by the buggy code)
    cursor.execute("""
        SELECT id, full_name, match_name, team_id
        FROM players
        WHERE nationality = 'China'
          AND (id LIKE 'ai_youth_%' OR full_name GLOB '[A-Z]*')
    """)
    
    rows = cursor.fetchall()
    if not rows:
        # Broader query: any player with China nationality whose name
        # doesn't look Chinese (contains only ASCII letters)
        cursor.execute("""
            SELECT id, full_name, match_name, team_id
            FROM players
            WHERE nationality = 'China'
              AND full_name GLOB '*[a-z]*'
        """)
        rows = cursor.fetchall()
    
    if not rows:
        print("No players found that need fixing.")
        conn.close()
        return
    
    used_names = set()
    updates = []
    
    for player_id, old_full, old_match, team_id in rows:
        # Generate a unique Chinese name
        for _ in range(100):
            surname = random.choice(SURNAMES)
            given = random.choice(GIVEN_NAMES)
            full = f"{surname} {given}"
            match = surname  # match_name uses surname only (like other nationalities)
            if full not in used_names:
                used_names.add(full)
                break
        
        team_name = "Unknown"
        if team_id:
            cursor.execute("SELECT name FROM teams WHERE id = ?", (team_id,))
            row = cursor.fetchone()
            if row:
                team_name = row[0]
        
        updates.append((full, match, player_id))
        print(f"  {old_full:30s} → {full:10s}  ({team_name})")
    
    cursor.executemany(
        "UPDATE players SET full_name = ?, match_name = ? WHERE id = ?",
        updates
    )
    conn.commit()
    conn.close()
    
    print(f"\nFixed {len(updates)} player(s) ✅")


if __name__ == "__main__":
    db_path = find_save_file(sys.argv[1] if len(sys.argv) > 1 else None)
    print(f"Fixing players in: {db_path}\n")
    fix_players(db_path)
